**IMPORTAR LIBRERIAS Y DATASETS**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# LIBRERIAS DE VISUALIZACION QUE GENERAN GRAFICOS INTERACTIVOS
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.subplots as sp

In [2]:
df_conversions = pd.read_csv("../DATASETS/digital_marketing_campaign_dataset.csv")
df_conversions.head(10)

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,6,9,4,688,IsConfid,ToolConfid,1
1,8001,69,Male,41760,Email,Retention,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,2,7,2,3459,IsConfid,ToolConfid,1
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,11,2,8,2337,IsConfid,ToolConfid,1
3,8003,32,Female,44085,PPC,Conversion,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,2,2,0,2463,IsConfid,ToolConfid,1
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,6,6,8,4345,IsConfid,ToolConfid,1
5,8005,25,Female,42925,Social Media,Awareness,9579.388247,0.153795,0.161316,6,2.125850,7.752831,95,5,8,0,3316,IsConfid,ToolConfid,1
6,8006,38,Female,25615,Referral,Awareness,7302.899852,0.040975,0.060977,42,1.753995,10.698672,54,14,3,6,930,IsConfid,ToolConfid,1
7,8007,56,Female,57083,Social Media,Conversion,5324.283667,0.052878,0.188946,48,2.626015,2.987817,96,9,3,0,2983,IsConfid,ToolConfid,1
8,8008,36,Female,140788,Email,Retention,9421.250951,0.023536,0.112585,13,5.472843,14.287421,73,4,8,5,460,IsConfid,ToolConfid,1
9,8009,40,Male,130764,Social Media,Awareness,6229.193333,0.066641,0.169786,22,1.135665,4.613312,14,8,4,8,3789,IsConfid,ToolConfid,1

**DICCIONARIO DE DATOS**

**CustomerID**          =       ID del cliente

**Age**                 =       Edad del cliente

**Gender**              =       Genero del cliente

**Income**              =       Ingresos $ del cliente

**CampaignChannel**     =       Canal donde se realizó la campaña digital

**CampaignType**        =       Tipo de campaña digital: Conversión, Retención de clientes, etc

**AdSpend**             =       Monto invertido en la campaña de marketing en USD

**ClickThroughRate**    =       Tasa a la que los clientes hacen clic en el contenido de marketing

**ConversionRate**      =       Tasa de conversión

In [3]:
cantidad_conversiones_medio = df_conversions.groupby("CampaignChannel")["Conversion"].sum().sort_values(ascending=False).reset_index()
cantidad_conversiones_medio.rename(columns={
        "Conversion":"Cantidad de conversiones",
        "CampaignChannel": "Canal"
    }, inplace=True)
cantidad_conversiones_medio

          Canal  Cantidad de conversiones
0      Referral                      1518
1           PPC                      1461
2           SEO                      1359
3         Email                      1355
4  Social Media                      1319

In [4]:
# SE GENERA UN GRAFICO EN PLOTLY PARA VISUALIZAR LA CANTIDAD DE CONVERSIONES
fig_conversiones = px.bar(cantidad_conversiones_medio, x="Canal", y="Cantidad de conversiones", title="Cantidad de conversiones por canal de marketing",
color="Cantidad de conversiones", color_continuous_scale="Viridis")

# GENERAR ETIQUETAS EN LAS BARRAS
for i, row in cantidad_conversiones_medio.iterrows():
    fig_conversiones.add_annotation(
        x=row["Canal"],
        y=row["Cantidad de conversiones"],
        text=f"{row['Cantidad de conversiones']}"
    )
fig_conversiones.show()

**CONCLUSIONES:** Se observa que los medios Referral y PPC son los que más generan conversiones

In [5]:
# CREAR PORCENTAJE DE CONVERSION POR GENERO
porcentaje_conversion_genero = df_conversions.groupby(["Gender"])["Conversion"].sum().reset_index()

# RENOMBRAR COLUMNAS
porcentaje_conversion_genero.rename(columns={
        "Conversion":"Cantidad de conversiones",
        "Gender": "Genero"
    }, inplace=True)
porcentaje_conversion_genero

   Genero  Cantidad de conversiones
0  Female                      4240
1    Male                      2772

In [9]:
# GENERAR GRAFICO DE BARRAS CON LA TABLA porcentaje_conversion_genero
fig_conversion_genero = px.bar(porcentaje_conversion_genero, x="Genero", y="Cantidad de conversiones", title="Porcentaje de conversiones por género y edad")

# GENERAR ETIQUETAS EN LAS BARRAS
for i, row in porcentaje_conversion_genero.iterrows():
    fig_conversion_genero.add_annotation(
        x=row["Genero"],
        y=row["Cantidad de conversiones"],
        text=f"{row['Cantidad de conversiones']}"
    )

fig_conversion_genero.show()

In [20]:
# AÑADIR CONVERSIONES Y NO CONVERSIONES POR GENERO
conversiones_no_conversiones_por_genero = df_conversions.groupby(["Gender", "Conversion"])["Conversion"].count().reset_index(name="Cantidad").replace({
    0: "No Conversion", 
    1: "Conversion"
    }).rename(columns={
    "Gender": "Genero",
    "Conversion": "Conversion",
    "Cantidad": "Cantidad de conversiones y no conversiones"
})
conversiones_no_conversiones_por_genero

   Genero     Conversion  Cantidad de conversiones y no conversiones
0  Female  No Conversion                                         599
1  Female     Conversion                                        4240
2    Male  No Conversion                                         389
3    Male     Conversion                                        2772

In [25]:
# CREAR GRAFICO DE BARRAS APILADAS CON LA TABLA conversiones_no_conversiones_por_genero
fig_conversiones_apiladas = px.bar(conversiones_no_conversiones_por_genero, x="Genero", y="Cantidad de conversiones y no conversiones", color="Conversion", title="Cantidad de conversiones y no conversiones por género")

# AÑADIR ETIQUETAS EN LAS BARRAS SIN FLECHAS

for i, row in conversiones_no_conversiones_por_genero.iterrows():
    fig_conversiones_apiladas.add_annotation(
        x=row["Genero"],
        y=row["Cantidad de conversiones y no conversiones"],
        text=f"{row['Cantidad de conversiones y no conversiones']}"
    )

fig_conversiones_apiladas.show()